### PR TITLE
Adds compat for Interpolations@0.13

### PR DESCRIPTION
**Pull request by ferrolho**

### CODE REVIEW

**Comment by ferrolho** [comment]
Ah, never mind. There's #49 already.

**Comment by rdeits** [comment]
It turns out that we need https://github.com/tkoolen/ValkyrieRobot.jl/pull/11 to fix a StaticArrays compatibility issue. Once that's in, then I'll fix the Interpolations compat.

**Comment by rdeits** [comment]
I think what happened is that JuliaRegistries/General at some point added compatibility bounds to existing packages. That resulted in ValkyrieRobot.jl having an upper bound of StaticArrays 0.12, but we need StaticArrays 1.0 for...some other package (I can't quite tell). Anyway, this should all be resolved by a new ValkyrieRobot.jl release.

**Comment by ferrolho** [comment]
Understood. Thanks! :slightly_smiling_face:

**Pull request closed without merging**
