### PR TITLE
Adds scaling to transform in `setelement!`

### PR DESCRIPTION
**Pull request by ferrolho**
Complements https://github.com/JuliaRobotics/MechanismGeometries.jl/pull/18/.

### CODE REVIEW

**Comment by ferrolho** [comment]
Scaling seems to be working, well... sort of. Some links seem to be missing?

Screenshot from 2019-09-03 01-14-53

**Comment by tkoolen** [comment]
Could you post the code you used to create that image?

**Comment by ferrolho** [comment]
> Could you post the code you used to create that image?

https://github.com/ferrolho/ANYmalRobot.jl

**Comment by ferrolho** [comment]
I will close this according to https://github.com/JuliaRobotics/MechanismGeometries.jl/pull/18#issuecomment-527292236:
> - no accompanying MeshCatMechanisms PR is needed; no need to coordinate releases.

**Pull request closed without merging**
